### ISSUE TITLE
Mysql db can't be created.

### ISSUE THREAD

**Issue by ToonMeynen** [alexggolovin/alexggolovin-opencart#2]

**Comment by alexggolovin** [comment]
I would like to check the puppet output messages with possible errors, also please clarify OS repo and version, all module configuration changes which been done by your manually.

Thanks,

**Comment by ToonMeynen** [comment]
I’m would like to create a branch where I can put all my modifications to. But I’m quit new with github so I still need to figure out how to do this properly.

**Comment by alexggolovin** [comment]
Let me figure out how is it possible, pay attention it was tested with added EPEL repo, so please double check again.

Thanks,

**Comment by ToonMeynen** [comment]
I fixed the mysql issues with this. In servers.pp.

    mysql::db { $mydb:
        user          => "${mydb}",
        password      => "${mypass}",
        host          => 'localhost',
    }

**Comment by alexggolovin** [comment]
Solution: you can fork this repository and initicate pull request after changes will be done, I would approve it and we'll get a new merge!

**Comment by alexggolovin** [comment]
I've checked, looks like everything works well regardless some selinux erros on CentOS-6, opencart database created and all required php modules installed, I was able to create login into opencart after created admin user:

puppet agent -t
info: Loading facts in /var/lib/puppet/lib/facter/concat_basedir.rb
info: Loading facts in /var/lib/puppet/lib/facter/facter_dot_d.rb
info: Loading facts in /var/lib/puppet/lib/facter/root_home.rb
info: Loading facts in /var/lib/puppet/lib/facter/puppet_vardir.rb
info: Loading facts in /var/lib/puppet/lib/facter/staging_windir.rb
info: Loading facts in /var/lib/puppet/lib/facter/pe_version.rb
info: Loading facts in /var/lib/puppet/lib/facter/staging_http_get.rb
info: Caching catalog for centos6.softservecom.com
info: Applying configuration version '1430992715'
notice: /Stage[main]/Opencart::Depend/Package[php-gd]/ensure: created
notice: /Stage[main]/Opencart::Depend/Package[php-mcrypt]/ensure: created
notice: /Stage[main]/Opencart::Depend/Package[php-mysql]/ensure: created
notice: /Stage[main]/Apache::Service/Service[httpd]/ensure: ensure changed 'stopped' to 'running'
info: /Stage[main]/Apache::Service/Service[httpd]: Unscheduling refresh on Service[httpd]
notice: /Stage[main]/Opencart::Download/Package[wget]/ensure: created
notice: /Stage[main]/Opencart::Download/Exec[wget-https://github.com/alexggolovin/opencart/raw/master/opencart-2.0.2.0.zip]/returns: executed successfully
notice: /Stage[main]/Opencart::Extract/Package[unzip]/ensure: created
notice: /Stage[main]/Opencart::Extract/Exec[unzip-/tmp/temp.zip]/returns: executed successfully
notice: /Stage[main]/Opencart::Deploy/Exec[cp-opencart.local]/returns: executed successfully
err: /Stage[main]/Opencart::Deploy/Exec[selinux-opencart.local]/returns: change from notrun to 0 failed: setsebool -P httpd_anon_write=1 && chcon -R -t public_content_rw_t /var/www/opencart.local/ && mv /var/www/opencart.local/admin/opencart_deployed.txt /var/www/opencart.local/admin/opencart_deployed_date.txt returned 255 instead of one of [0] at /etc/puppet/modules/opencart/manifests/deploy.pp:24
notice: Finished catalog run in 69.16 seconds

**Comment by alexggolovin** [comment]
ToonMeynen, 
Please double check that it fixed in new 1.1.2 release and let me know when issure can be closed.

Thanks,

**Comment by alexggolovin** [comment]
Issue fixed in 1.1.3 release
