### ISSUE TITLE
SSL verification failure.

### ISSUE THREAD

**Issue by ToonMeynen** [alexggolovin/alexggolovin-opencart#3]
I have tested the new module. (v1.1.3) On Centos 6.4 I ran into the following error.

``` bash
Error: wget https://github.com/alexggolovin/opencart/raw/master/opencart-2.0.2.0.zip -O /tmp/temp.zip returned 5 instead of one of [0]
Error: /Stage[main]/Opencart::Download/Exec[wget-https://github.com/alexggolovin/opencart/raw/master/opencart-2.0.2.0.zip]/returns: change from notrun to 0 failed: wget https://github.com/alexggolovin/opencart/raw/master/opencart-2.0.2.0.zip -O /tmp/temp.zip returned 5 instead of one of [0]
```

I ran the following command manualy on the node 

``` bash
[root@webstore tmp]# wget https://github.com/alexggolovin/opencart/raw/master/opencart-2.0.2.0.zip -O /tmp/temp.zip
--2015-05-11 06:14:29--  https://github.com/alexggolovin/opencart/raw/master/opencart-2.0.2.0.zip
Resolving github.com... 192.30.252.129
Connecting to github.com|192.30.252.129|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/alexggolovin/opencart/master/opencart-2.0.2.0.zip [following]
--2015-05-11 06:14:34--  https://raw.githubusercontent.com/alexggolovin/opencart/master/opencart-2.0.2.0.zip
Resolving raw.githubusercontent.com... 23.235.43.133, 199.27.78.133
Connecting to raw.githubusercontent.com|23.235.43.133|:443... connected.
ERROR: certificate common name “www.github.com” doesn’t match requested host name “raw.githubusercontent.com”.
To connect to raw.githubusercontent.com insecurely, use ‘--no-check-certificate’.
```

It suggests using --no-check-certificate. A bit dirty but it works.

**Comment by alexggolovin** [comment]
Hi ToonMeynen ,

 Thanks for your notification about errors with 1.1.3 module release, I just already deployed release 1.1.4 and checked it on CentOS release 6.6, with successufll opencart deploy and this output:

notice: /File[/var/www/opencart.local]/ensure: created
notice: /File[25-opencart.local.conf]/ensure: defined content as '{md5}1a0dcbcd5f64d2f7e67a88200e5cc5ef'
info: Concat[25-opencart.local.conf]: Scheduling refresh of Class[Apache::Service]
notice: /Stage[main]/Opencart::Depend/Package[php-gd]/ensure: created
notice: /Stage[main]/Opencart::Depend/Package[php-mcrypt]/ensure: created
notice: /Stage[main]/Opencart::Depend/Package[php-mysql]/ensure: created
info: Class[Apache::Service]: Scheduling refresh of Service[httpd]
notice: /Stage[main]/Apache::Service/Service[httpd]/ensure: ensure changed 'stopped' to 'running'
info: /Stage[main]/Apache::Service/Service[httpd]: Unscheduling refresh on Service[httpd]
notice: /Stage[main]/Opencart::Download/Exec[wget-https://github.com/alexggolovin/opencart/raw/master/opencart-2.0.2.0.zip]/returns: executed successfully
notice: /Stage[main]/Opencart::Extract/Exec[unzip-/tmp/temp.zip]/returns: executed successfully
notice: /Stage[main]/Opencart::Deploy/Exec[cp-opencart.local]/returns: executed successfully

 It's might be your network proxy settings configurations, try to run wget command "wget-https://github.com/alexggolovin/opencart/raw/master/opencart-2.0.2.0.zip" manually from console on your server.

 Please let me know about results, it would be helpful because I don't have a chance to test it on CentOS6.4 version at this moment,  it was just tested on CentOS-6.6 by me for now.

Thanks!

**Comment by ToonMeynen** [comment]
Manual wget on mij node. Return the following.

``` bash
[root@webstore tmp]# wget https://github.com/alexggolovin/opencart/raw/master/opencart-2.0.2.0.zip
--2015-05-11 08:03:04--  https://github.com/alexggolovin/opencart/raw/master/opencart-2.0.2.0.zip
Resolving github.com... 192.30.252.130
Connecting to github.com|192.30.252.130|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/alexggolovin/opencart/master/opencart-2.0.2.0.zip [following]
--2015-05-11 08:03:10--  https://raw.githubusercontent.com/alexggolovin/opencart/master/opencart-2.0.2.0.zip
Resolving raw.githubusercontent.com... 23.235.43.133
Connecting to raw.githubusercontent.com|23.235.43.133|:443... connected.
ERROR: certificate common name “www.github.com” doesn’t match requested host name “raw.githubusercontent.com”.
To connect to raw.githubusercontent.com insecurely, use ‘--no-check-certificate’.
```

**Comment by ToonMeynen** [comment]
Why not just download the package from opencart.com ?

**Comment by alexggolovin** [comment]
So, it's clear now, seems like "https" wget/github problem, first you've got response 302 which was redirection to https://raw.githubusercontent.com site, and then www.github.com and raw.githubusercontent.com cert's mismatch error. 
  What about download from opencart.com I just used their repo and installation file clone links in my module to be sure it's always available from the internet. So, as I wrote in the README.md file module description:
  " all required params.pp parameters must be preconfigured before this module usage beginning" and "$content = 'https://github.com/alexggolovin/opencart/raw/master/opencart-2.0.2.0.zip'" option can and must be changed to any available trusted link include opencart official download link.

Thanks,
